# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Windows_Front_End\add_patient_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
import uuid

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QMessageBox



class Ui_Add_DB_Patient(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 340, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 391, 261))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 5, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 6, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #################################################################################
        #################################################################################

        """ ************************************************************************* """
        """ *                                                                       * """
        """ *                               ПОЕХАЛИ                                 * """
        """ *                                                                       * """
        """ ************************************************************************* """

        #################################################################################
        #################################################################################

        self.lineEdit_5.setMaxLength(11)  # ограничения для снилса
        validator = QRegExpValidator(QRegExp(r'[0-9]*'))
        self.lineEdit_5.setValidator(validator)  # валидация только на цифры

        validator = QRegExpValidator(QRegExp(r'[a-zA-Zа-яА-Я]*'))
        self.lineEdit.setValidator(validator)  # валидация только на буквы
        self.lineEdit_2.setValidator(validator)  # валидация только на буквы
        self.lineEdit_3.setValidator(validator)  # валидация только на буквы

        #################################################################################

        self.pushButton.clicked.connect(self.add_db_patient)
        self.norm_comboBox()

        #################################################################################
    #################################################################################

    def norm_comboBox(self):

        self.comboBox.clear()

        db = sqlite3.connect('DataBase\\database.db')
        cursor = db.cursor()
        self.conn = db
        self.cursor = cursor
        self.cursor.execute("SELECT name_of_the_disease FROM disease")
        sql = cursor.fetchall()
        self.disease = []
        for i in sql:
            self.disease.append(i[0])
        self.comboBox.addItems(self.disease)

    #################################################################################
    def add_db_patient(self):

        patient = 'patient'
        self.ID = uuid.uuid4()

        f = self.lineEdit.text()
        i = self.lineEdit_2.text()
        o = self.lineEdit_3.text()
        address = self.lineEdit_4.text()
        snils = self.lineEdit_5.text()
        data_b = self.dateEdit.text()
        diagnoz = self.comboBox.currentText()


        snils = str(snils)
        if len(snils) > 11 or len(snils) == 0:
            self.lineEdit_5.setText('')

            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)  # восклицательный
            msg.setText("ERROR!")
            msg.setInformativeText('Ошибка СНИЛС!')
            msg.setWindowTitle("Add")
            msg.exec_()

        elif len(f) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)  # восклицательный
            msg.setText("ERROR!")
            msg.setInformativeText('Ошибка ФАМИЛИИ!')
            msg.setWindowTitle("Add")
            msg.exec_()

        elif len(i) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)  # восклицательный
            msg.setText("ERROR!")
            msg.setInformativeText('Ошибка ИМЕНИ!')
            msg.setWindowTitle("Add")
            msg.exec_()

        elif len(o) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)  # восклицательный
            msg.setText("ERROR!")
            msg.setInformativeText('Ошибка ОТЧЕСТВА!')
            msg.setWindowTitle("Add")
            msg.exec_()

        elif len(address) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)  # восклицательный
            msg.setText("ERROR!")
            msg.setInformativeText('Ошибка АДРЕСА!')
            msg.setWindowTitle("Add")
            msg.exec_()

        else:
            while len(snils) < 11:
                snils = '0' + snils
            snils = f'{snils[0:3]}-{snils[3:6]}-{snils[6:9]} {snils[9:11]}'

            db = sqlite3.connect('DataBase\\database.db')
            cursor = db.cursor()

            cursor.execute(f'''CREATE TABLE IF NOT EXISTS patient(
                    ID TEXT,
                    fio_ TEXT,
                    address_ TEXT,
                    data_b_ TEXT,
                    diagnoz TEXT,
                    snils TEXT PRIMARY KEY,
                    cD1_ TEXT,
                    cD2_ TEXT,
                    cD3_ TEXT,
                    ScD1_ TEXT,
                    ScD2_ TEXT,
                    ScD3_ TEXT,
                    H_ TEXT,
                    c_ TEXT,
                    Array_S BLOW,
                    Array_P BLOW
                    )''')

            db.commit()
            cD1 = ''
            cD2 = ''
            cD3 = ''
            ScD1 = ''
            ScD2 = ''
            ScD3 = ''
            H = ''
            c = ''
            Array_S = ''
            Array_P = ''
            fio__ = f'{f} {i} {o}'

            cursor.execute(f'SELECT snils FROM patient WHERE snils ="{snils}"')
            if cursor.fetchone() is None:
                cursor.execute(f'INSERT INTO patient VALUES('
                               f'"{self.ID}",'
                               f'"{fio__}",'
                               f'"{address}",'
                               f'"{data_b}",'
                               f'"{diagnoz}",'
                               f'"{snils}",'
                               f'"{cD1}",'
                               f'"{cD2}",'
                               f'"{cD3}",'
                               f'"{ScD1}",'
                               f'"{ScD2}",'
                               f'"{ScD3}",'
                               f'"{H}",'
                               f'"{c}",'
                               f'"{Array_S}",'
                               f'"{Array_P}")'
                               )
            #     cursor.execute("ALTER TABLE patient ADD COLUMN Array_P BLOW")
                # cursor.execute("ALTER TABLE patient DROP COLUMN Array_S")
                db.commit()

                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)  # восклицательный
                msg.setText("Добавлено!")
                msg.setInformativeText('Результат добавлен в БД!')
                msg.setWindowTitle("Add")
                msg.exec_()

                self.lineEdit.clear()
                self.lineEdit_2.clear()
                self.lineEdit_3.clear()
                self.lineEdit_4.clear()
                self.lineEdit_5.clear()

            else:
                print('ERROr_Add_db')
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Ошибка")
                msg.setInformativeText('Такая запись уже имеется!')
                msg.setWindowTitle("Error")
                msg.exec_()

    #################################################################################
    #################################################################################

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Добавить пациента"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.label_6.setText(_translate("MainWindow", "Год рождения"))
        self.label_8.setText(_translate("MainWindow", "Снилс"))
        self.label_7.setText(_translate("MainWindow", "Диагноз"))
        self.label_2.setText(_translate("MainWindow", "Фамилия"))
        self.label_5.setText(_translate("MainWindow", "Адрес"))
        self.label_3.setText(_translate("MainWindow", "Имя"))
        self.label_4.setText(_translate("MainWindow", "Отчество"))
        self.comboBox.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Заболевание сердца"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Add_DB_Patient()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
